// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaticMeshComponent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_StaticMeshComponent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_StaticMeshComponent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ChanneldGlobalStruct.pb.h"
#include "unreal_common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_StaticMeshComponent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_StaticMeshComponent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_StaticMeshComponent_2eproto;
namespace channeldgenpb {
class StaticMeshComponentState;
struct StaticMeshComponentStateDefaultTypeInternal;
extern StaticMeshComponentStateDefaultTypeInternal _StaticMeshComponentState_default_instance_;
}  // namespace channeldgenpb
PROTOBUF_NAMESPACE_OPEN
template<> ::channeldgenpb::StaticMeshComponentState* Arena::CreateMaybeMessage<::channeldgenpb::StaticMeshComponentState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace channeldgenpb {

// ===================================================================

class StaticMeshComponentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:channeldgenpb.StaticMeshComponentState) */ {
 public:
  inline StaticMeshComponentState() : StaticMeshComponentState(nullptr) {}
  ~StaticMeshComponentState() override;
  explicit PROTOBUF_CONSTEXPR StaticMeshComponentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StaticMeshComponentState(const StaticMeshComponentState& from);
  StaticMeshComponentState(StaticMeshComponentState&& from) noexcept
    : StaticMeshComponentState() {
    *this = ::std::move(from);
  }

  inline StaticMeshComponentState& operator=(const StaticMeshComponentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline StaticMeshComponentState& operator=(StaticMeshComponentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StaticMeshComponentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const StaticMeshComponentState* internal_default_instance() {
    return reinterpret_cast<const StaticMeshComponentState*>(
               &_StaticMeshComponentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StaticMeshComponentState& a, StaticMeshComponentState& b) {
    a.Swap(&b);
  }
  inline void Swap(StaticMeshComponentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StaticMeshComponentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StaticMeshComponentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StaticMeshComponentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StaticMeshComponentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StaticMeshComponentState& from) {
    StaticMeshComponentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StaticMeshComponentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "channeldgenpb.StaticMeshComponentState";
  }
  protected:
  explicit StaticMeshComponentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropStaticmeshFieldNumber = 2,
    kRemovedFieldNumber = 1,
  };
  // optional .unrealpb.UnrealObjectRef prop_staticmesh = 2;
  bool has_prop_staticmesh() const;
  private:
  bool _internal_has_prop_staticmesh() const;
  public:
  void clear_prop_staticmesh();
  const ::unrealpb::UnrealObjectRef& prop_staticmesh() const;
  PROTOBUF_NODISCARD ::unrealpb::UnrealObjectRef* release_prop_staticmesh();
  ::unrealpb::UnrealObjectRef* mutable_prop_staticmesh();
  void set_allocated_prop_staticmesh(::unrealpb::UnrealObjectRef* prop_staticmesh);
  private:
  const ::unrealpb::UnrealObjectRef& _internal_prop_staticmesh() const;
  ::unrealpb::UnrealObjectRef* _internal_mutable_prop_staticmesh();
  public:
  void unsafe_arena_set_allocated_prop_staticmesh(
      ::unrealpb::UnrealObjectRef* prop_staticmesh);
  ::unrealpb::UnrealObjectRef* unsafe_arena_release_prop_staticmesh();

  // bool removed = 1;
  void clear_removed();
  bool removed() const;
  void set_removed(bool value);
  private:
  bool _internal_removed() const;
  void _internal_set_removed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:channeldgenpb.StaticMeshComponentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::unrealpb::UnrealObjectRef* prop_staticmesh_;
    bool removed_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_StaticMeshComponent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StaticMeshComponentState

// bool removed = 1;
inline void StaticMeshComponentState::clear_removed() {
  _impl_.removed_ = false;
}
inline bool StaticMeshComponentState::_internal_removed() const {
  return _impl_.removed_;
}
inline bool StaticMeshComponentState::removed() const {
  // @@protoc_insertion_point(field_get:channeldgenpb.StaticMeshComponentState.removed)
  return _internal_removed();
}
inline void StaticMeshComponentState::_internal_set_removed(bool value) {
  
  _impl_.removed_ = value;
}
inline void StaticMeshComponentState::set_removed(bool value) {
  _internal_set_removed(value);
  // @@protoc_insertion_point(field_set:channeldgenpb.StaticMeshComponentState.removed)
}

// optional .unrealpb.UnrealObjectRef prop_staticmesh = 2;
inline bool StaticMeshComponentState::_internal_has_prop_staticmesh() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.prop_staticmesh_ != nullptr);
  return value;
}
inline bool StaticMeshComponentState::has_prop_staticmesh() const {
  return _internal_has_prop_staticmesh();
}
inline const ::unrealpb::UnrealObjectRef& StaticMeshComponentState::_internal_prop_staticmesh() const {
  const ::unrealpb::UnrealObjectRef* p = _impl_.prop_staticmesh_;
  return p != nullptr ? *p : reinterpret_cast<const ::unrealpb::UnrealObjectRef&>(
      ::unrealpb::_UnrealObjectRef_default_instance_);
}
inline const ::unrealpb::UnrealObjectRef& StaticMeshComponentState::prop_staticmesh() const {
  // @@protoc_insertion_point(field_get:channeldgenpb.StaticMeshComponentState.prop_staticmesh)
  return _internal_prop_staticmesh();
}
inline void StaticMeshComponentState::unsafe_arena_set_allocated_prop_staticmesh(
    ::unrealpb::UnrealObjectRef* prop_staticmesh) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.prop_staticmesh_);
  }
  _impl_.prop_staticmesh_ = prop_staticmesh;
  if (prop_staticmesh) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:channeldgenpb.StaticMeshComponentState.prop_staticmesh)
}
inline ::unrealpb::UnrealObjectRef* StaticMeshComponentState::release_prop_staticmesh() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::unrealpb::UnrealObjectRef* temp = _impl_.prop_staticmesh_;
  _impl_.prop_staticmesh_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::unrealpb::UnrealObjectRef* StaticMeshComponentState::unsafe_arena_release_prop_staticmesh() {
  // @@protoc_insertion_point(field_release:channeldgenpb.StaticMeshComponentState.prop_staticmesh)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::unrealpb::UnrealObjectRef* temp = _impl_.prop_staticmesh_;
  _impl_.prop_staticmesh_ = nullptr;
  return temp;
}
inline ::unrealpb::UnrealObjectRef* StaticMeshComponentState::_internal_mutable_prop_staticmesh() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.prop_staticmesh_ == nullptr) {
    auto* p = CreateMaybeMessage<::unrealpb::UnrealObjectRef>(GetArenaForAllocation());
    _impl_.prop_staticmesh_ = p;
  }
  return _impl_.prop_staticmesh_;
}
inline ::unrealpb::UnrealObjectRef* StaticMeshComponentState::mutable_prop_staticmesh() {
  ::unrealpb::UnrealObjectRef* _msg = _internal_mutable_prop_staticmesh();
  // @@protoc_insertion_point(field_mutable:channeldgenpb.StaticMeshComponentState.prop_staticmesh)
  return _msg;
}
inline void StaticMeshComponentState::set_allocated_prop_staticmesh(::unrealpb::UnrealObjectRef* prop_staticmesh) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.prop_staticmesh_);
  }
  if (prop_staticmesh) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(prop_staticmesh));
    if (message_arena != submessage_arena) {
      prop_staticmesh = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, prop_staticmesh, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.prop_staticmesh_ = prop_staticmesh;
  // @@protoc_insertion_point(field_set_allocated:channeldgenpb.StaticMeshComponentState.prop_staticmesh)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace channeldgenpb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_StaticMeshComponent_2eproto
