// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaticMeshComponent.proto

#ifdef _MSC_VER
#	pragma warning(disable: 4125)
#	pragma warning(disable: 4647)
#	pragma warning(disable: 4668)
#	pragma warning(disable: 4800)
#	pragma warning(disable: 4946)
#endif

#include "StaticMeshComponent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace channeldgenpb {
PROTOBUF_CONSTEXPR StaticMeshComponentState::StaticMeshComponentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.prop_staticmesh_)*/nullptr
  , /*decltype(_impl_.removed_)*/false} {}
struct StaticMeshComponentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StaticMeshComponentStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StaticMeshComponentStateDefaultTypeInternal() {}
  union {
    StaticMeshComponentState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StaticMeshComponentStateDefaultTypeInternal _StaticMeshComponentState_default_instance_;
}  // namespace channeldgenpb
static ::_pb::Metadata file_level_metadata_StaticMeshComponent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_StaticMeshComponent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_StaticMeshComponent_2eproto = nullptr;

const uint32_t TableStruct_StaticMeshComponent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::channeldgenpb::StaticMeshComponentState, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::channeldgenpb::StaticMeshComponentState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::channeldgenpb::StaticMeshComponentState, _impl_.removed_),
  PROTOBUF_FIELD_OFFSET(::channeldgenpb::StaticMeshComponentState, _impl_.prop_staticmesh_),
  ~0u,
  0,
};
static const ::_pbi::MigrationSchema schemas_StaticMeshComponent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::channeldgenpb::StaticMeshComponentState)},
};

static const ::_pb::Message* const file_default_instances_StaticMeshComponent_2eproto[] = {
  &::channeldgenpb::_StaticMeshComponentState_default_instance_._instance,
};

const char descriptor_table_protodef_StaticMeshComponent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031StaticMeshComponent.proto\022\rchanneldgen"
  "pb\032\032ChanneldGlobalStruct.proto\032\023unreal_c"
  "ommon.proto\"x\n\030StaticMeshComponentState\022"
  "\017\n\007removed\030\001 \001(\010\0227\n\017prop_staticmesh\030\002 \001("
  "\0132\031.unrealpb.UnrealObjectRefH\000\210\001\001B\022\n\020_pr"
  "op_staticmeshBFZDchanneld.clewcat.com/ch"
  "anneld/examples/channeld-ue-tps/channeld"
  "genpbb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_StaticMeshComponent_2eproto_deps[2] = {
  &::descriptor_table_ChanneldGlobalStruct_2eproto,
  &::descriptor_table_unreal_5fcommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_StaticMeshComponent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_StaticMeshComponent_2eproto = {
    false, false, 293, descriptor_table_protodef_StaticMeshComponent_2eproto,
    "StaticMeshComponent.proto",
    &descriptor_table_StaticMeshComponent_2eproto_once, descriptor_table_StaticMeshComponent_2eproto_deps, 2, 1,
    schemas_StaticMeshComponent_2eproto, file_default_instances_StaticMeshComponent_2eproto, TableStruct_StaticMeshComponent_2eproto::offsets,
    file_level_metadata_StaticMeshComponent_2eproto, file_level_enum_descriptors_StaticMeshComponent_2eproto,
    file_level_service_descriptors_StaticMeshComponent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_StaticMeshComponent_2eproto_getter() {
  return &descriptor_table_StaticMeshComponent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_StaticMeshComponent_2eproto(&descriptor_table_StaticMeshComponent_2eproto);
namespace channeldgenpb {

// ===================================================================

class StaticMeshComponentState::_Internal {
 public:
  using HasBits = decltype(std::declval<StaticMeshComponentState>()._impl_._has_bits_);
  static const ::unrealpb::UnrealObjectRef& prop_staticmesh(const StaticMeshComponentState* msg);
  static void set_has_prop_staticmesh(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::unrealpb::UnrealObjectRef&
StaticMeshComponentState::_Internal::prop_staticmesh(const StaticMeshComponentState* msg) {
  return *msg->_impl_.prop_staticmesh_;
}
void StaticMeshComponentState::clear_prop_staticmesh() {
  if (_impl_.prop_staticmesh_ != nullptr) _impl_.prop_staticmesh_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
StaticMeshComponentState::StaticMeshComponentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:channeldgenpb.StaticMeshComponentState)
}
StaticMeshComponentState::StaticMeshComponentState(const StaticMeshComponentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StaticMeshComponentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.prop_staticmesh_){nullptr}
    , decltype(_impl_.removed_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_prop_staticmesh()) {
    _this->_impl_.prop_staticmesh_ = new ::unrealpb::UnrealObjectRef(*from._impl_.prop_staticmesh_);
  }
  _this->_impl_.removed_ = from._impl_.removed_;
  // @@protoc_insertion_point(copy_constructor:channeldgenpb.StaticMeshComponentState)
}

inline void StaticMeshComponentState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.prop_staticmesh_){nullptr}
    , decltype(_impl_.removed_){false}
  };
}

StaticMeshComponentState::~StaticMeshComponentState() {
  // @@protoc_insertion_point(destructor:channeldgenpb.StaticMeshComponentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StaticMeshComponentState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.prop_staticmesh_;
}

void StaticMeshComponentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StaticMeshComponentState::Clear() {
// @@protoc_insertion_point(message_clear_start:channeldgenpb.StaticMeshComponentState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.prop_staticmesh_ != nullptr);
    _impl_.prop_staticmesh_->Clear();
  }
  _impl_.removed_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StaticMeshComponentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool removed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.removed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .unrealpb.UnrealObjectRef prop_staticmesh = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_prop_staticmesh(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StaticMeshComponentState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:channeldgenpb.StaticMeshComponentState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool removed = 1;
  if (this->_internal_removed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_removed(), target);
  }

  // optional .unrealpb.UnrealObjectRef prop_staticmesh = 2;
  if (_internal_has_prop_staticmesh()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::prop_staticmesh(this),
        _Internal::prop_staticmesh(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:channeldgenpb.StaticMeshComponentState)
  return target;
}

size_t StaticMeshComponentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:channeldgenpb.StaticMeshComponentState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .unrealpb.UnrealObjectRef prop_staticmesh = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.prop_staticmesh_);
  }

  // bool removed = 1;
  if (this->_internal_removed() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StaticMeshComponentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StaticMeshComponentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StaticMeshComponentState::GetClassData() const { return &_class_data_; }


void StaticMeshComponentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StaticMeshComponentState*>(&to_msg);
  auto& from = static_cast<const StaticMeshComponentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:channeldgenpb.StaticMeshComponentState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_prop_staticmesh()) {
    _this->_internal_mutable_prop_staticmesh()->::unrealpb::UnrealObjectRef::MergeFrom(
        from._internal_prop_staticmesh());
  }
  if (from._internal_removed() != 0) {
    _this->_internal_set_removed(from._internal_removed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StaticMeshComponentState::CopyFrom(const StaticMeshComponentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:channeldgenpb.StaticMeshComponentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StaticMeshComponentState::IsInitialized() const {
  return true;
}

void StaticMeshComponentState::InternalSwap(StaticMeshComponentState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StaticMeshComponentState, _impl_.removed_)
      + sizeof(StaticMeshComponentState::_impl_.removed_)
      - PROTOBUF_FIELD_OFFSET(StaticMeshComponentState, _impl_.prop_staticmesh_)>(
          reinterpret_cast<char*>(&_impl_.prop_staticmesh_),
          reinterpret_cast<char*>(&other->_impl_.prop_staticmesh_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StaticMeshComponentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_StaticMeshComponent_2eproto_getter, &descriptor_table_StaticMeshComponent_2eproto_once,
      file_level_metadata_StaticMeshComponent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace channeldgenpb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::channeldgenpb::StaticMeshComponentState*
Arena::CreateMaybeMessage< ::channeldgenpb::StaticMeshComponentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::channeldgenpb::StaticMeshComponentState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
